### ISSUE TITLE
Support for custom model 

### ISSUE THREAD

**Issue by aqibsaeed** [brunneis/ernie#18]
Hi,

Thanks for a nice library. Is it possible to use a custom BERT (huggingface) model to be used in sentence classification pipeline?

**Comment by brunneis** [comment]
You can load any custom model compatible with the locked version of Transformers that Ernie is using. I haven't had time to adapt it yet to the latest version so some of the recent architectures may not work. In the same way you could be able to use a dumped model trained with Ernie and use it directly with Transformers.
