### ISSUE TITLE
Pandas requirement

### ISSUE THREAD

**Issue by surya-narayanan** [brunneis/ernie#5]
Hi, 

I'm trying to install ernie and it seems to require an inconsistent version of pandas. 

https://pasteboard.co/IXXIry1.png

Can you advise on what to do? 

This runs on colab just fine. 

It also throws errors that it cannot find TensorFlow even though tf is installed.

**Comment by brunneis** [comment]
Hi @surya-narayanan. It is strange. This requirement was removed in previous versions. For some reason, pip is collecting for you an old version of Ernie. Please, force the installation with `pip3 install ernie==0.0.22b0`.

In any case, about the error you are receiving, I think the problem is that you have an older version of Python than 3.6.1 which is the minimum that Pandas 1.0.1 requires. Maybe an older version of pip itself, which you can upgrade with `pip3 install --upgrade pip`.

Let me know if that works.

**Comment by surya-narayanan** [comment]
I tried the first option. It seems you have versions: 0.0.1b0, 0.0.2b0, 0.0.4b0, 0.0.5b0, 0.0.6b0. Should I try 0.0.2b0?

**Comment by surya-narayanan** [comment]
Hmm... I cannot upgrade my Python on my VM. Any idea how I can do that? I am trying sudo apt-get install python3.7

**Comment by brunneis** [comment]
No, those are the first versions: https://pypi.org/project/ernie/#history. I think I added after those versions a minimum Python requirement. Try updating pip. Which is the Python version you are using? ( `python3 --version`)

**Comment by surya-narayanan** [comment]
I am using 3.5 on my VM and 3.7 locally.

**Comment by brunneis** [comment]
Which distribution and version are you using (OS)? That's the problem, the minimum requirement is Python 3.6.

**Comment by surya-narayanan** [comment]
I am running a linux VM and am on OS locally. I tried upgrading my python 

Got the following errors. 
E: Unable to locate package python3.7
E: Couldn't find any package by glob 'python3.7'
E: Couldn't find any package by regex 'python3.7'

Any idea what to do?

**Comment by brunneis** [comment]
Paste here the output of: `cat /etc/*release*`

**Comment by surya-narayanan** [comment]
Also, installing worked while running this on colab. 

But, running it with distillbert produced the following error. 

Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs`

I tried 

1. setting a steps_per_epoch kwarg in classifier.fine_tune but this kwarg was rejected because steps_per_epoch argument got multiple arguments in classifier.fine_tune. I haven't looked into the code yet but do you know how I can fix the "out of data" issue for Dilstilbert?
2. also changed mytraining_batch_size=1 but it still didn't work. It should work with a really small training batch size since I am only processing one example at a time, it should have enough data...

**Comment by surya-narayanan** [comment]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by brunneis** [comment]
I think that in Ubuntu Xenial the last version available in the official repos is 3.5. Try installing the Anaconda Python distribution.

**Comment by surya-narayanan** [comment]
I couldn't find it on anaconda.org. Is it under 'ernie'?

**Comment by brunneis** [comment]
https://repo.anaconda.com/archive/Anaconda3-2019.10-Linux-x86_64.sh
