### ISSUE TITLE
Not having enough data even with training_batch_size=1 

### ISSUE THREAD

**Issue by surya-narayanan** [brunneis/ernie#6]
Running it with distillbert produced the following error. 

Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs`

I tried 

1. setting a steps_per_epoch kwarg in classifier.fine_tune but this kwarg was rejected because steps_per_epoch argument got multiple arguments in classifier.fine_tune. I haven't looked into the code yet but do you know how I can fix the "out of data" issue for Dilstilbert?
2. also changed mytraining_batch_size=1 but it still didn't work. It should work with a really small training batch size since I am only processing one example at a time, it should have enough data...

_Originally posted by @surya-narayanan in https://github.com/brunneis/ernie/issues/5#issuecomment-596065667_

**Comment by brunneis** [comment]
Hi @surya-narayanan, I can't reproduce the problem. Can you give more details (i.e., the dataset used, code)? Thanks.
