### ISSUE TITLE
Other language supporting plan?

### ISSUE THREAD

**Issue by zhang-yunke** [brunneis/ernie#7]
Hi there, fist thank you for your great work. It looks like this project only supports English now, is there any plan for supporting other languages such as Chinese or French?

**Comment by brunneis** [comment]
Hi @ywwhxxtw. Definitely! The idea is supporting all the available models for HuggingFace Transformers, including those shared by the community (https://huggingface.co/models). I'm currently quite busy but I'll try to solve this and the other issues in the following days.

**Comment by zhang-yunke** [comment]
Wonderful! looking forward to your good news :)
