### ISSUE TITLE
AutoModel cannot be imported

### ISSUE THREAD

**Issue by realjanpaulus** [brunneis/ernie#8]
When I try to import `ernie`, I got the following error:

```python
from transformers import (
ImportError: cannot import name 'AutoModel' from 'transformers' (/home/janpaulus/miniconda3/envs/ernie/lib/python3.7/site-packages/transformers/__init__.py)
```

There seems to be a problem with the `AutoModel` class which isn't essential for the `ernie.py` file (at least for my usage).

My workaround for the `ernie.py` file is the "removal" of the AutoModel import:

```python
import tensorflow as tf
import numpy as np
from transformers import (
    AutoTokenizer,
    #AutoModel,
    TFAutoModelForSequenceClassification,
)
```

Maybe the transformers version 2.4.1 isn't the right one?

**Comment by brunneis** [comment]
Hi @realjanpaulus, I can't reproduce the error. Can you successfully run the [Colab example](https://colab.research.google.com/drive/10lmqZyAHFP_-x4LxIQxZCavYpPqcR28c)?

I can import that class locally too. Are you sure the transformers version is the 2.4.1? (that version is actually forced when installing `ernie`). Maybe you created a file called `transformers.py` which is interfering?

```
>>> import transformers
transformers.__version__
>>> transformers.__version__
'2.4.1'
>>> from transformers import AutoModel
>>> 
```
