### ISSUE TITLE
Train using >1 df columns

### ISSUE THREAD

**Issue by addadda023** [brunneis/ernie#9]
In load_dataset.py, sentences and labels are hardcoded to take first and second column of input dataframe. Is there a way to use Ernie if I have >1 features?  
 
```
sentences = list(dataframe[dataframe.columns[0]])
labels = dataframe[dataframe.columns[1]].values
```

**Comment by brunneis** [comment]
Hi @addadda023, you can only train a model with text. If the other features are textual you can try with concatenating them or just adding them as new rows.

**Comment by addadda023** [comment]
Ok. Yes the other features are also text. Thanks.
